### ISSUE TITLE
maybe make its own repo?

### ISSUE THREAD

**Issue by jovo** [openconnectome/open-connectome#121]
i know we've discussed this before, and i know it depends on the ocp stack,
i view it as a lightweight "plug-in", which is a great example of the kind of plug-ins that people can write against the ocp stack, much like the tilecache service.

i think smaller more modular repos, in general, is better practice, especially since there is no reason that this function needs to live on the same server as the back-end.

@randalburns - opine?

**Comment by alexbaden** [comment]
Right now, if you install ocp you get ocpviz, and it just works. No setup is required, and any token / project / channel in your OCP install is instantly viewable. To do this, I have to hook into the OCP django install, so ocpviz can't run standalone at the moment. We could change that, but it introduces some complications and I wouldn't want to do that until later. 

We can split it into its own repo, but that adds steps for anyone who wants to install OCP + ocpviz and be up and running. We would also have to reorg some of the OCP repo (having settings.py checked in isn't great from a plugins standpoint). 

The tilecache is a better example because it uses the API. I don't use the API by default (but I can), because I wanted a really easy way to just view stuff as you ingest it. 

Last note -- with our current ocp setup (which I won't post too much about here, this being public), we would not be able to have ocpviz and ocp in separate repos and enjoy all the git functionality we currently use. This is theoretically less of an issue for end users, but you can't (to my knowledge) have a git repo in a git reop, which would mean you would need to be much better about making releases to update to new versions.

**Comment by jovo** [comment]
let's discuss again once ocpviz is deployed, i still haven't seen it actually work on most of the data.  if it does, let's not make any major changes before SfN.

@alexbaden @kunallillaney you'll tell me when its pushed?

**Comment by alexbaden** [comment]
Done. https://github.com/openconnectome/NeuroDataViz
